### ISSUE TITLE
license information?

### ISSUE THREAD

**Issue by bcdarwin** [BIC-MNI/minc-widgets#6]
Some programs have licenses in the source code, but ecat2hdf5, mincanon and volunfold don't.  Are these using the usual MINC license?

**Comment by vfonov** [comment]
I would imagine that package license applies.

**Comment by vfonov** [comment]
Now, where is the package license?

**Comment by andrewjanke** [comment]
This one is my bad. I have updated the scripts in question. Yes, there probably should be a package licence but there isn't. minc-widgets was always just a collection of various stuff from the back cupboard.
